#include<stdio.h>
#include<stdlib.h>
#include<string.h>
void main()
{
FILE *intermediate,*optab,*symtab,*listing,*proglength,*objcode;
int i,locctr,start,programlength,length=0,textstartaddr;
char opcode[20],operand[20],label[20],mnemonic[20],code[20],value[20],textrecord[70];
optab=fopen("optab.txt","r");
intermediate=fopen("intermediate.txt","r");
symtab=fopen("symtab.txt","r");
proglength=fopen("proglength.txt","r");
objcode=fopen("objcode.txt","w");
listing=fopen("listing.txt","w");
fscanf(intermediate,"\t\t%s\t\t%s\t\t%s",label,opcode,operand);
fprintf(listing,"\t\t%s\t\t%s\t\t%s\n",label,opcode,operand);
if(strcmp(opcode,"START")==0)
{
fscanf(proglength,"%d",&programlength);
start=atoi(operand);
fprintf(objcode,"H^%s^%06d^%06d\n",label,start,programlength);
}
fscanf(intermediate,"%d\t\t%s\t\t%s\t\t%s",&locctr,label,opcode,operand);
textstartaddr=locctr;
strcpy(textrecord,"");
while(strcmp(opcode,"END")!=0)
{
char objectcode[10]="";
fprintf(listing,"%d\t\t%s\t\t%s\t\t%s",locctr,label,opcode,operand);
if(strcmp(opcode,"BYTE")==0)
{
if(operand[0]=='C'&&operand[1]=='\'')
{
if(strcmp(operand,"C'EOF'")==0)
strcpy(objectcode,"454F46");
else
{
for(i=2;i<strlen(operand)-1;i++)
sprintf(objectcode+strlen(objectcode),"%02X",operand[i]);
}
}
}
else if(strcmp(opcode,"WORD")==0)
sprintf(objectcode,"%06d",atoi(operand));
/*else if(strcmp(opcode,"RESB")==0)
sprintf(objectcode,"%06d",atoi(operand));
else if(strcmp(opcode,"RESW")==0)
sprintf(objectcode,"%06d",atoi(operand));*/
else
{
rewind(optab);
while(fscanf(optab,"%s\t\t%s",mnemonic,code)!=EOF)
{
if(strcmp(opcode,mnemonic)==0)
{
strcpy(objectcode,code);
break;
}
}
rewind(symtab);
while(fscanf(symtab,"%s\t\t%s",label,value)!=EOF)
{
if(strcmp(operand,label)==0)
{
sprintf(objectcode+strlen(objectcode),"%04d",atoi(value));
break;
}
}
}
fprintf(listing,"\t\t%s\n",objectcode);
if(length+strlen(objectcode)>60)
{
fprintf(objectcode,"T^%06d^%02X^%s\n",textstartaddr,(length/2),textrecord);
strcpy(textrecord,"");
textstartaddr=locctr;
length=0;
}
if(strlen(objectcode)>0)
{
strcat(textrecord,objectcode);
strcat(textrecord,"^");
length+=strlen(objectcode);
}
fscanf(intermediate,"%d\t\t%s\t\t%s\t\t%s",&locctr,label,opcode,operand);
}
if(length>0)
{
textrecord[strlen(textrecord)-1]='\0';
fprintf(objcode,"T^%06d^%02X^%s\n",textstartaddr,(length/2),textrecord);
}
fprintf(listing,"%d\t\t%s\t\t%s\t\t%s",locctr,label,opcode,operand);
fprintf(objcode,"E^%06d\n",start);
fclose(intermediate);
fclose(symtab);
fclose(optab);
fclose(listing);
fclose(proglength);
}
